// <auto-generated />
using System;
using ContactListProject.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactListProject.Migrations
{
    [DbContext(typeof(ContactsContext))]
    [Migration("20230110172537_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactListProject.model.Contact", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<int?>("ContactRowId")
                        .HasColumnType("int");

                    b.HasKey("RowId");

                    b.HasIndex("ContactRowId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ContactListProject.model.Contact", b =>
                {
                    b.HasOne("ContactListProject.model.Contact", null)
                        .WithMany("Subordinates")
                        .HasForeignKey("ContactRowId");
                });

            modelBuilder.Entity("ContactListProject.model.Contact", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
